fix(vtl_adapter) : Fix the process of sending the state topic when passing "End Line"
eve-autonomy/v2i_interface pull request #42
Opened 2023-06-05 02:13 UTC by sfukuta

2023-06-06 05:27 UTC, yn-mrse requested changes

2023-06-06 22:16 UTC, yn-mrse requested changes

2023-06-06 22:16 UTC, yn-mrse commented on vtl_adapter/src/vtl_state_converter.cpp
> +  if (msg->commands.size() > 0){
可読性・メンテナンス性が落ちるためearly returnをお願いします。
また、.size() > 0チェック⇒ empty()チェックへの置き換えでよいかと思います。

2023-06-06 22:16 UTC, yn-mrse commented on vtl_adapter/src/vtl_state_converter.cpp
> +  if (!finalized_only) {
可読性が落ちるためearly return をお願いしま。

2023-06-07 00:49 UTC, sfukuta commented on vtl_adapter/src/vtl_state_converter.cpp
> +  if (!finalized_only) {
https://github.com/eve-autonomy/v2i_interface/pull/42/commits/3e92b58b2e1fe3c377168d922fa8a68c5f60d45c 対応しました。

2023-06-07 00:49 UTC, sfukuta commented on vtl_adapter/src/vtl_state_converter.cpp
> +  if (msg->commands.size() > 0){
https://github.com/eve-autonomy/v2i_interface/pull/42/commits/9cbec316b9530b0f4a6da9347ead9f8e11801dc7 対応しました

2023-06-07 06:19 UTC, sfukuta commented on vtl_adapter/src/vtl_state_converter.cpp
> +  const auto finalize_only = isFinalized(msg);
https://github.com/eve-autonomy/v2i_interface/pull/42/commits/a33a11aa29ab121e9a0162b65e7cb46dc5dee0b1 対応しました

2023-06-07 06:19 UTC, sfukuta commented on vtl_adapter/src/vtl_state_converter.cpp
> +  if (!finalized_only) {
https://github.com/eve-autonomy/v2i_interface/pull/42/commits/2b1fc63a8a3812c31e7c401eb2a48bd1f2f7ea0f 追加対応しました。

2023-06-07 06:19 UTC, sfukuta commented on vtl_adapter/src/vtl_state_converter.cpp
> +  if (msg->commands.size() > 0){
https://github.com/eve-autonomy/v2i_interface/pull/42/commits/2b1fc63a8a3812c31e7c401eb2a48bd1f2f7ea0f 追加対応しました

2023-06-07 06:42 UTC, yn-mrse requested changes

2023-06-07 06:42 UTC, yn-mrse commented on vtl_adapter/src/vtl_state_converter.cpp
> +  const auto output_state = createState(is_all_commands_finalized);
```suggestion
  OutputStateArr output_state;
  output_state.stamp = state_->stamp;
  if (!is_all_commands_finalized) {
    output_state = createState(is_all_commands_finalized);
  }
```

2023-06-07 06:58 UTC, sfukuta commented on vtl_adapter/src/vtl_state_converter.cpp
> +  const auto output_state = createState(is_all_commands_finalized);
```suggestion
  OutputStateArr output_state;
  if (!is_all_commands_finalized) {
     output_state.stamp = state_->stamp;
  }else{
     output_state = createState();
  }
```

2023-06-07 07:05 UTC, yn-mrse requested changes

2023-06-07 07:05 UTC, yn-mrse commented on vtl_adapter/src/vtl_state_converter.cpp
> +  const auto output_state = createState(is_all_commands_finalized);
```suggestion
	  OutputStateArr output_state;
	  if (!is_all_commands_finalized) {
	    output_state = createState(is_all_commands_finalized);
	  }
	  output_state.stamp = state_->stamp;
```

2023-06-07 08:37 UTC, yn-mrse approved these changes

2023-06-08 02:28 UTC, merged