feat(v2i_interface): add test tool by tkeasygui
eve-autonomy/v2i_interface pull request #55
Opened 2024-09-24 02:39 UTC by asa-naki

# Description
#52 でv2i_interfaceのテストツールを削除した。
削除したことによって、設備連携を行う機能の動作確認ができなくなった。
よって、代替となるテストツールをtkeasyGUIを使って作成した。

# Related link
https://tier4.atlassian.net/browse/AEAP-1018
# Test

### GUI画面
1. tkeasyguiをインストールする
pip3 install tkeasygui
2.ros2 launch v2i_interface v2i_interface_test.launch.xml
を実施して、GUI画面がでることを確認した。
![image](https://github.com/user-attachments/assets/e2edf72e-dc21-416d-afe3-310ab41ece63)

既存のpysimpleGUIによる、UDP通信で車両BXPを模擬した情報を送信方法が変化ないことを確認した。

## 機能確認
テストツールの機能確認として、

- v2i_interfaceからUDP通信で送信された情報を受信情報
- 設備を模擬した送信情報

を確認した。
具体的には、v2i_interfaceにUDP通信で車両BXPを模擬した情報を送信して、設備連携機能の評価項目を実施した。

### 送信情報
- 停留所設備連携
- 設備連携VTL
が設定されている環境でPlanning_simulatorを実施し、
で設備機器の情報を送信できていることを確認しました。
### 受信情報
v2i_interfaceからUDP通信で送信された情報

2024-09-25 04:00 UTC, yn-mrse commented
@asa-naki 
想定ユーザはREADMEを見ることが前提になっているのでしょうか？
package.xmlへ記載のうえrosdep installによる導入か、ecu_system_setup(セットアップ用別リポジトリ)にて導入を自動化しないと使える状態にならないのではないでしょうか？

2024-09-25 05:47 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +from rclpy.qos import QoSDurabilityPolicy, QoSProfile
使われていないようです. [Module imported but unused (F401)](https://www.flake8rules.com/rules/F401.html)

2024-09-25 05:47 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +import signal
使われていないようです. [Module imported but unused (F401)](https://www.flake8rules.com/rules/F401.html)

2024-09-25 07:12 UTC, peeeechi reviewed
ご対応ありがとうございます！
何箇所か気になった点をコメントしておりますので、ご確認いただけますと幸いです

2024-09-25 07:12 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        global send_write
bool の変数なので is_~~~~のような変数名が望ましいと思います

2024-09-25 07:12 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        global recv_write
ditto

2024-09-25 07:12 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +            message, cli_addr = self._recv_socket.recvfrom(self._buff_size)
`cli_addr` は使用されていないようです。
基本的には削除が良いと思いますが、
今回のようなtupleのunpackでは  `_` を使って不使用であることを伝えるのが良いと思います。
[local variable 'id' is assigned to but never used(F841)](https://www.flake8rules.com/rules/F841.html)

2024-09-25 07:12 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        del self._dummy
`del self._dummy` の前に 
`self._th_close = True` は必要ない？

2024-09-25 11:04 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +import signal
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/2491c24256fecedb720139661538e9aae176d7c3
で対応しました

2024-09-25 11:05 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +from rclpy.qos import QoSDurabilityPolicy, QoSProfile
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/2491c24256fecedb720139661538e9aae176d7c3

で対応しました

2024-09-25 11:14 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        global send_write
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/f63b51fe908c86e2fa0f5f3375f218dd14a606dd
で対応しました。

2024-09-25 11:15 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        global recv_write
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/a501112597bb2a875ff03a83288c28d9f010190c
で対応しました。

2024-09-25 11:36 UTC, asa-naki commented
@yn-mrse 

> package.xmlへ記載のうえrosdep installによる導入

については、pipコマンドがrosdep installに対応していないようです。
なので、本PRでは対応せず、ecu_system_setup(セットアップ用別リポジトリ)にて導入
の方針としたいと思います。
(remarkなどにこのecu_system_setupで対応することを記載しておこうと思います）

2024-09-25 11:44 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +            message, cli_addr = self._recv_socket.recvfrom(self._buff_size)
使用されていないで合っていました。
方針としては、削除で良いと思います。
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/dfabdd78259b173b3461cfcc60b3e00dcb6d14dc
で対応しました。

2024-09-25 12:44 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +from rclpy.qos import QoSDurabilityPolicy, QoSProfile
`message` が tuple になってしまっているので、
`message, _ = self._recv_socket.recvfrom(self._buff_size)` としてあげた方が良いように思います

2024-09-25 12:44 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +            message, cli_addr = self._recv_socket.recvfrom(self._buff_size)
`message` が tuple になってしまっているので、
`message, _ = self._recv_socket.recvfrom(self._buff_size)` としてあげた方が良いように思います

2024-09-25 12:52 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        global send_write
ご対応ありがとうございます！
良いように思います！

2024-09-25 12:52 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        global recv_write
ご対応ありがとうございます！
良いように思います！

2024-09-26 01:05 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +            message, cli_addr = self._recv_socket.recvfrom(self._buff_size)
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/8c0e456b509426511f70ba7b2c673386528431c2
で対応し直しました。

2024-09-26 01:07 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        del self._dummy
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/783408ec967225e62b06bfdb65cd1f53237b5eae
で対応しました。

2024-09-26 01:20 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        th_infra_ecu = threading.Thread(target=self.recv_from_v2i_interface)
daemon = True にした方が安全な気がします。
https://docs.python.org/ja/3/library/threading.html#threading.Thread.daemon

2024-09-26 01:21 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        th_main = threading.Thread(target=self.main_loop)
diito

2024-09-26 01:30 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        th_infra_ecu = threading.Thread(target=self.recv_from_v2i_interface)
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/7cb580f2d6569812c78545aa1d9640674824844f
で対応済み

2024-09-26 01:30 UTC, asa-naki commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        th_main = threading.Thread(target=self.main_loop)
https://github.com/eve-autonomy/v2i_interface/pull/55/commits/7cb580f2d6569812c78545aa1d9640674824844f
で対応済み

2024-09-26 02:09 UTC, asa-naki commented
@yn-mrse 
今回スコープはライブラリを変更して模擬ツールとして動作できることを対象としているため、
ECUセットアップへの入れ込みは別対応とします。

2024-09-26 02:19 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        del self._dummy
ご対応ありがとうございます！
良いように思います！

2024-09-26 02:19 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +            message, cli_addr = self._recv_socket.recvfrom(self._buff_size)
ご対応ありがとうございます！
良いように思います！

2024-09-26 02:20 UTC, peeeechi commented on v2i_interface/scripts/test/v2i_interface_test.py
> +        th_main = threading.Thread(target=self.main_loop)
ご対応ありがとうございます！
良いように思います！

2024-09-26 02:22 UTC, peeeechi commented
@asa-naki 
コメント箇所への対応ありがとうございます！

@yn-mrse 
私は本内容でApprovalして良いように思います！

2024-09-26 13:21 UTC, yn-mrse requested changes

2024-09-26 13:25 UTC, yn-mrse approved these changes

2024-09-26 14:08 UTC, merged